# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f327278c1fbd1612fbee5bab64f546f68331e71a3d414d198fdc84f86a76955718842f1104871f21021fbd09eff40742f155e4950a6c79dc1642e3939394f936
  recaptcha:
    public_key: 6Ldx49cSAAAAAGU12yCsksZyRVuqV75jzkJY1cyx
    private_key: 6Ldx49cSAAAAACjZo6LftEUkHn3rRCrLXp5I68es
  devise: 9e7dc3d149b4fc286fb371e87ce54c4aa926b143f20d5fc2ef758ae13aaffbefd99696c2b0379bf1f2bfd662e132bb7fa0ec5b0426eb5d659a374cc9750e01c5

test:
  secret_key_base: 08457f5e32a537e3ecf114cfad37b82090783d562df167c1829fc64fb7825db9c7bc018bd44ebb8107c1892068c08456c7079925b4fa67348d897ee4414cdcbe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  recaptcha:
    public_key: <%= ENV["RECAPTCHA_PUBLIC"] %>
    private_key: <%= ENV["RECAPTCHA_PRIVATE"] %>
  devise: <%= ENV["DEVISE"] %>
  access: <%= ENV["ACCESS"] %>
  mail: <%= ENV["MAIL"] %>